name: Build And Push Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      # 拉取项目代码
      - name: Checkout
        uses: actions/checkout@v3
      # 登录到 GitHub
      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # 构建和推送镜像
      - name: Build And Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/lemonneko/reminds-bot-beta:latest
